npmScopes:
 fortawesome:
   npmAlwaysAuth: true
   npmRegistryServer: "https://npm.fontawesome.com/"
   npmAuthToken: 68DC228D-A2D3-4D64-BC84-5E2421D43C48
 awesome.me:
   npmAlwaysAuth: true
   npmRegistryServer: "https://npm.fontawesome.com/"
   npmAuthToken: 68DC228D-A2D3-4D64-BC84-5E2421D43C48